### ISSUE TITLE
Majority of content fails to play

### ISSUE THREAD

**Issue by nilbarc** [maxgalbu/xbmc.plugin.video.nba#10]
Anything like The Starters, Highlights, Top Plays etc. fails to play. NBA TV live, archived games and live games play fine.

v15.2 Isengard on Kodibuntu.

Pertinent log section is attached.

[kodi_error_log.txt](https://github.com/maxgalbu/xbmc.plugin.video.nba/files/84133/kodi_error_log.txt)

**Comment by maxgalbu** [comment]
Everything is working fine for me, except the starters... I'll check now

**Comment by maxgalbu** [comment]
Should work now, it was an issue with some of the video titles

**Comment by nilbarc** [comment]
Unfortunately no luck. Installed the updated version and still the same issue. I've attached a log from trying various categories within the plugin. Please let me know if there's anything I can do.
[kodi_error_log2.txt](https://github.com/maxgalbu/xbmc.plugin.video.nba/files/85110/kodi_error_log2.txt)

**Comment by nilbarc** [comment]
(and sorry, I don't have privileges to reopen the issue as you closed it)

**Comment by maxgalbu** [comment]
All the videos streams are using rtmp, and I see this: 

```
Unable to load librtmp.so.1, reason: librtmp.so.1: cannot open shared object file: No such file or directory
```

Did you update something recently? Try to do:

```
sudo apt-get install librtmp1
```

**Comment by nilbarc** [comment]
Yes, that's fixed it. Thank you so much!
